
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbfezuyehuvmdayylsrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiZmV6dXllaHV2bWRheXlsc3JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDk1ODYsImV4cCI6MjA2MTUyNTU4Nn0._7k6J8HrODs6P0HtHR_MAdGosjRjUGR5ASAb6cPpsU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'promptflow-auth'
  }
});
